import polars as pl, numpy as np, sys, os
from typing import List

def reject_samples(
    ip: str,
    columns: List[str] | None = None,
    criterion: str = 'amplitude',
    threshold: float = 100e-6,
    # Output filename is always autogenerated, no custom output allowed
) -> str:
    print(f"[PROC] Rejection: {ip}, columns={columns}, criterion={criterion}, threshold={threshold}")
    df = pl.read_parquet(ip)
    if columns is None:
        columns = [c for c in df.columns if c not in ['time', 'sfreq']]
    mask = np.ones(len(df), dtype=bool)
    for col in columns:
        sig = df[col].to_numpy()
        if criterion == 'amplitude':
            mask &= np.abs(sig) < threshold
        elif criterion == 'gradient':
            grad = np.abs(np.gradient(sig))
            mask &= grad < threshold
        elif criterion == 'flatline':
            mask &= np.std(sig) > threshold
        else:
            print(f"[PROC] Unknown criterion: {criterion}"); sys.exit(1)
    print(f"[PROC] Retaining {np.sum(mask)} of {len(df)} samples")
    result = df.filter(mask)
    out_file = f"{ip.replace('.parquet', '')}_rej.parquet"
    try:
        result.write_parquet(out_file)
    except Exception as e:
        print(f"[PROC] ERROR: Could not write output file: {out_file}")
        raise
    print(f"[PROC] Output: {out_file}")
    return out_file

if __name__ == '__main__':
    import ast
    a = sys.argv
    if len(a) < 2:
        print("[PROC] Usage: python rejection_processor.py <input.parquet> [columns] [criterion] [threshold]")
        sys.exit(1)
    columns = ast.literal_eval(a[2]) if len(a) > 2 and a[2] not in ('', 'None') else None
    criterion = a[3] if len(a) > 3 else 'amplitude'
    threshold = float(a[4]) if len(a) > 4 else 100e-6
    reject_samples(a[1], columns, criterion, threshold)
